services:
  api:
    build: ./backend       
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    command: bash -c "python manage.py runserver 0.0.0.0:8000"

  web:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - './frontend:/frontend'
      - '/app/node_modules'