# Generated by Django 3.0.14 on 2023-01-19 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20230119_1704'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fetaures',
            new_name='Features',
        ),
    ]
